# Application name and main settings
spring:
  application:
    name: city-explorer
  main:
    allow-bean-definition-overriding: true

  # DataSource configuration for PostgreSQL
  datasource:
    url: jdbc:postgresql://${HOST:localhost}/${DB_NAME:city-explorer}?sslmode=require
    username: ${USERNAME:postgres}
    password: ${PASSWORD:password}

  # JPA (Java Persistence API) configuration
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update  # Change to 'update' in production to retain data
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

# Spring Boot application server settings
server:
  port: ${APPLICATION_PORT:8080}  # Port on which the application will run

# Jackson configuration for JSON serialization/deserialization
jackson:
  deserialization:
    READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true  # Deserialize unknown enum values using default
  serialization:
    INDENT_OUTPUT: true  # Pretty-print JSON responses

# Security configuration
security:
  jwt:
    secret: ${JWT_SECRET:09a2f721c66d652a1a58b7e3380b0127c8d12d2d14c6e0ebf0341b183fb3f0e1}  # JWT secret key (default)
    expiration: ${EXPIRATION:840000}  # JWT expiration time in milliseconds
    refreshMs: ${REFRESH_TIME_MS:9840000}  # Refresh token validity in milliseconds

# Springdoc OpenAPI configuration
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Exchange API key and rate URL
exchange:
  base-url: ${EXCHANGE_URL:http://api.exchangeratesapi.io/v1 }
  key: ${ACCESS_KEY:access_key}

# Weather API key and url
weather:
  base-url: ${WEATHER_URL:http://api.openweathermap.org}
  key: ${ACCESS_KEY:access_key}
  limit: ${LIMIT:1}

# World Bank Open API
worldBank:
  base-url: ${WORLD_BANK_URL:http://api.worldbank.org/v2}
