spring:
  application:
    name: city-explorer
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://ep-snowy-boat-a5s4k706.us-east-2.aws.neon.tech:5432/city-explorer?sslmode=require
    username: city-explorer_owner
    password: QGpbPrKY7B0u
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true
    serialization:
      INDENT_OUTPUT: true
  security:
    jwt:
      secret: ${JWT_SECRET:09a2f721c66d652a1a58b7e3380b0127c8d12d2d14c6e0ebf0341b183fb3f0e1}
      expiration: ${EXPIRATION:840000}
      refreshMs: ${REFRESH_TIME_MS:9840000}
server:
  port: ${APPLICATION_PORT:8080}